from . import hue_op_department
from . import hue_semester
from . import hue_certificate
from . import hue_nationality
from . import hue_city
from . import hue_registration_block
from . import hue_student_status
from . import hue_course_grade_equivalent
from . import hue_op_academic_term
from . import hue_op_academic_year
from . import hue_joining_years
from . import hue_installments
from . import hue_assessments
from . import hue_grades
from . import hue_levels
